from datetime import datetime
from typing import Protocol

from shopagent.domain.models import (
    AuditEvent,
    FeedbackRecord,
    InteractionRecord,
    KnowledgeCandidate,
)


class OperationsStore(Protocol):
    async def record_interaction(self, record: InteractionRecord) -> None: ...
    async def get_interaction(self, trace_id: str) -> InteractionRecord | None: ...
    async def save_feedback(self, feedback: FeedbackRecord) -> FeedbackRecord: ...
    async def get_feedback_by_idempotency(
        self, user_id: str, key: str
    ) -> FeedbackRecord | None: ...
    async def save_candidate(self, candidate: KnowledgeCandidate) -> None: ...
    async def get_candidate(self, candidate_id: str) -> KnowledgeCandidate | None: ...
    async def update_candidate(self, candidate: KnowledgeCandidate) -> None: ...
    async def update_candidate_status(
        self,
        candidate_id: str,
        expected_status: str,
        *,
        new_status: str,
        reviewed_by: str | None = None,
    ) -> bool: ...
    async def list_candidates(self, status: str | None = None) -> list[KnowledgeCandidate]: ...
    async def dashboard(self) -> dict: ...
    async def record_audit(self, event: AuditEvent) -> None: ...
    async def list_audit(self, limit: int = 100) -> list[AuditEvent]: ...
    async def save_task(self, task: dict, *, owner: str, expires_at: datetime) -> None: ...
    async def get_task(self, task_id: str, *, owner: str) -> dict | None: ...
